### PR TITLE
Add registry configuration

### PR DESCRIPTION
**Pull request by grachevko**

### CODE REVIEW

**Comment by jimsheldon** [comment]
Thanks for the contribution.

This looks good, I just need to get the CI pipeline working before I can merge. Unfortunately we are having some trouble with cloud.drone.io

**Comment by jimsheldon** [comment]
@grachevko I have moved the CI pipeline to a different drone instance, can you try pushing a change to your branch to trigger the pipeline now? Thanks

**Comment by grachevko** [comment]
@jimsheldon done

**Comment by viceice** [comment]
this is a breaking change for user who already add a proxy registry to the repository field 😕

**Pull request merged**
